sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
notifications:
    email:
        on_success: never
before_install:
script: ./travis.sh

